### ISSUE TITLE
Make teams always be a list?

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/translator_extensions#5]
Right now teams can either be a string or a list of strings.   In TRAPI, the trend has been towards removing this choice and making things always a list, which makes the processing of returns a bit simpler.

Maybe a similar change here would be appropriate.

**Comment by colleenXu** [comment]
I'm okay with that. @newgene What do you think? 

The change to allow either (it was originally only a list) was made before the relay, when I noticed that some people were registering and putting team's value as a string.

**Comment by newgene** [comment]
@colleenXu @cbizon I have no preference of either. Usually I'd prefer to "string+list" combination when "list" is a rare exception, otherwise, we would list just use "list". In this case, it's for translator internal use, the total number of cases are small enough, I would be good with whichever the group prefers.

so @colleenXu, I would suggest we do this:

* Get an idea how many of API metadata entries will need to be updated
* Briefly mention it at the next Arch call, just to confirm no strong objection to update API metadata to use list

If no strong objection, we can just modify the schema and enforce the change.

**Comment by colleenXu** [comment]
@cbizon Most APIs have only one team (76 out of the 83 annotated with x-translator). 

If we go with list only, there are 4 current API entries that would need to be updated from string -> one-element list.

**Comment by colleenXu** [comment]
Changes have been pushed from main to production branch, to make teams a list only.
